export const ActionType = {
  SET_BOTTOM: "SET_BOTTOM",
  SET_NAV: "SET_NAV",
  LOGGED_IN:"LOGGED_IN",
  LOG_OUT: 'LOG_OUT',
  SAVE_NAME:'SAVE_NAME',
  SET_LOADING:'SET_LOADING',
  REMOVE_LOADING:'REMOVE_LOADING',
};
