# Use postgres/example user/password credentials
version: "3.1"
name: db
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_db: {}
