import React from 'react';
import './global.css';
import { initAxiosInstance } from '@e-com/sdk';
import AxiosInitialized from '../components/AxiosInitialized';
export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  initAxiosInstance({
    baseURL: 'http://localhost:4000/api', // Example Base URL
    // other configuration settings...
  });
  return (
    <html lang="en">
      <AxiosInitialized></AxiosInitialized>
      <body>{children}</body>
    </html>
  );
}
