sources:
  - name: BookService
    handler:
      grpc:
        endpoint: 0.0.0.0:1000
        source: ../../libs/protos/book-service-proto/src/lib/book.v1.proto
  - name: AuthorService
    handler:
      grpc:
        endpoint: 0.0.0.0:1001
        source: ../../libs/protos/author-service-proto/src/lib/author.v1.proto
    transforms:
      - namingConvention:
          fieldNames: camelCase

additionalTypeDefs: |
  extend type author_v1_Author {
    books: [book_v1_Book]
   }

additionalResolvers:
  - targetTypeName: author_v1_Author
    targetFieldName: books
    requiredSelectionSet: |
      {
         _id
         name
         authorId
      }
    sourceName: BookService
    sourceTypeName: Query
    sourceFieldName: book_v1_BookService_GetList
    sourceArgs:
      id: '64289cdeba325e988b4300d3'
    result: books
