name: MS_LEARNING
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependecies
        run: yarn install --immutable
      - name: Run lint
        run: npx nx affected --target=test
      - name: Run build
        run: npx nx affected --target=test
      - name: Run tests
        run: npx nx affected --target=test
